insert into public.products (
  slug,
  name,
  brand,
  origin_country,
  short_description,
  editorial_description,
  price_gbp,
  weight_grams,
  category,
  tags,
  materials,
  supplier_url,
  stock_quantity,
  low_stock_threshold,
  is_published,
  is_featured
) values
  (
    'brass-pocket-clip',
    'Brass Pocket Clip',
    'Studio Sample',
    'Japan',
    'A small clip for keys, tickets, cables, and tiny travel order.',
    'It is not complicated. That is the point. A pocket clip that keeps loose daily fragments together without pretending to be gear.',
    28,
    12.4,
    'pocket',
    array['pocket', 'travel', 'keys'],
    array['brass'],
    'https://example.com/brass-pocket-clip',
    4,
    4,
    true,
    true
  ),
  (
    'flat-card-tool',
    'Flat Card Tool',
    'Archive Object',
    'South Korea',
    'Flat enough to disappear. Useful enough to come back.',
    'A simple card-format tool for the person who wants fewer separate things and fewer excuses.',
    34,
    18.0,
    'edc',
    array['edc', 'wallet', 'compact'],
    array['stainless steel'],
    'https://example.com/flat-card-tool',
    2,
    3,
    true,
    true
  ),
  (
    'paper-pocket-book',
    'Paper Pocket Book',
    'North Line',
    'Sweden',
    'The rare paper thing that earns the pocket.',
    'Small pages for notes that should not live in an app. Light enough to carry, nice enough to keep.',
    18,
    41.0,
    'travel',
    array['stationery', 'travel', 'notes'],
    array['paper'],
    'https://example.com/paper-pocket-book',
    8,
    3,
    true,
    false
  )
on conflict (slug) do update set
  name = excluded.name,
  brand = excluded.brand,
  origin_country = excluded.origin_country,
  short_description = excluded.short_description,
  editorial_description = excluded.editorial_description,
  price_gbp = excluded.price_gbp,
  weight_grams = excluded.weight_grams,
  category = excluded.category,
  tags = excluded.tags,
  materials = excluded.materials,
  supplier_url = excluded.supplier_url,
  stock_quantity = excluded.stock_quantity,
  low_stock_threshold = excluded.low_stock_threshold,
  is_published = excluded.is_published,
  is_featured = excluded.is_featured,
  updated_at = now();
